### ISSUE TITLE
Nullable types

### ISSUE THREAD

**Issue by droptable** [subins2000/phpfmt#8]
Currently phpF does not support the unary "?" notation for nullable types.

Example:
```php
function foo(?int $number): ?int
{
  if ($number === null) {
    $number = 42;
  }

  return $number;
}
```

The formatted result looks like this:

```php
function foo( ? int $number) : ? int
{
  if ($number === null) {
    $number = 42;
  }

  return $number;
}
```

The code still works as expected, but it doesn't look right to me.

Reference:
http://php.net/manual/de/migration71.new-features.php#migration71.new-features.nullable-types

**Comment by subins2000** [comment]
[Project Abandoned](https://github.com/subins2000/phpF#project-abandoned)
